### ISSUE TITLE
Remove superfluous job in deps workflow

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/github-config#591]
In the new dependencies workflow we have [a job](https://github.com/paketo-buildpacks/github-config/blob/13720cb54cbc6b637a9d69a12208a00d006e9ec3/implementation/.github/workflows/update-dependencies-from-metadata.yml#L9-L18) which only seems to emit a constant value:

```
jobs:
  select-go-version:
    name: Select Go Version
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.select-go-version.outputs.go-version }}
    steps:
      - name: Select Go Version
        id: select-go-version
        run: echo "::set-output name=go-version::>=1.18.0"
```

The only place that the `go-version` output is used is later on when we setup Go:

```
      - name: Setup Go '${{ needs.select-go-version.outputs.go-version }}'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.select-go-version.outputs.go-version }}
```

It would be better to hard-code the value in the job that uses it (i.e. the `Setup Go` step). If the intention is to parameterize it, we should use an input. Additional jobs require more runners and increase the risk of flakes and throttling/infrastructure issues.

cc @paketo-buildpacks/dependencies-maintainers
