### ISSUE TITLE
Ensure all workflows open/update issue on failure

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/github-config#664]
We find value in having github automatically open/update an issue when a workflow fails. We should ensure that all workflows managed by this repo perform this action.

We should also include relevant workflows for this repo itself (e.g. updating tools).

We have an established pattern for this e.g. [Language Family Push buildpackage failure hook](https://github.com/paketo-buildpacks/github-config/blob/add0b0417bd7aa662422f0257850fbefac739588/language-family/.github/workflows/push-buildpackage.yml#L77-L94):

```
  failure:
    name: Alert on Failure
    runs-on: ubuntu-22.04
    needs: [push]
    if: ${{ always() && needs.push.result == 'failure' }}
    steps:
    - name: File Failure Alert Issue
      uses: paketo-buildpacks/github-config/actions/issue/file@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: ${{ github.repository }}
        label: "failure:push"
        comment_if_exists: true
        issue_title: "Failure: Push Buildpackage workflow"
        issue_body: |
          Push Buildpackage workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
        comment_body: |
           Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
```
